### ISSUE TITLE
Doesn't seem to work at all in Xubuntu 20.04

### ISSUE THREAD

**Issue by fitzmorrispr** [AyatanaIndicators/ayatana-indicator-session#36]
My apologies if this is the wrong place, I couldn't find anywhere else to ask through google

I've installed the package using aptitude, and i've tried building it from this repository, and either way, when I attempt to run it I get the following output:
```
(process:561371): GLib-GObject-WARNING **: 14:41:39.630: invalid (NULL) pointer instance

(process:561371): GLib-GObject-CRITICAL **: 14:41:39.630: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(process:561371): GLib-GIO-CRITICAL **: 14:41:39.638: g_settings_get_value: assertion 'G_IS_SETTINGS (settings)' failed

(process:561371): GLib-CRITICAL **: 14:41:39.638: g_variant_get_string: assertion 'value != NULL' failed

(process:561371): GLib-CRITICAL **: 14:41:39.638: g_variant_unref: assertion 'value != NULL' failed

(process:561371): GLib-CRITICAL **: 14:41:39.638: g_variant_new_string: assertion 'string != NULL' failed

** (process:561371): WARNING **: 14:41:39.643: exiting: service couldn't acquire, or lost ownership of, busname
```

Am i merely missing some dependency that the deb didn't call for? I do have the xfce indicator applet running

**Comment by sunweaver** [comment]
@fitzmorrispr Thanks for reporting this issue. Please note that Xubuntu only switched to Ayatana Indicators in Xubuntu 21.04. With Xubuntu before then, you are basically on your own.

The DEB based distros (esp. Debian and Ubuntu) are currently switching over from Ubuntu Indicators to Ayatana Indicators (as the latter is maintained, the first is not anymore). In Ubuntu, the MATE and XFCE flavours switched over to Ayatana Indicators internally and things seem to work fine for them there.

Rebuilding all the Ayatana Indicators stack for Ubuntu 20.04 is a bad idea, because you need to patch several 3rd party packages (mate-indicator-applet, xfce4-indicator-plugin). Please don't do that, as it consumes time without benefit. 

I'll close this issue, because supporting Ayatana Indicators on top of Ubuntu 20.04 is beyond our scope here.

You might like to take a look at earlier blog posts of mine, but they are already quite old and we have moved on. Currently Ayatana Indicators are ripped apart and reconstructed again build system wise and you currently always need to rebuild all components to get the full picture.

Here the older blog posts:
https://sunweavers.net/blog/node/123 (IDO and vanilla GTK)
https://sunweavers.net/blog/node/78 (test Ayatana Indicators on Ubuntu 19.04)
